name: Generate ASCII ArtWork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Chectkout Repo
          uses: actions/checkout@v4
        
        - name: List Repo Files
          run: ls -ltrh
            
        - name: Exectue Shell Script
          run: ./ascii-script.sh
