name: Context dump

on:
  push:
    branches:
      - main

jobs:
  dump_context_to_logs:
      strategy:
        matrix:
         os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
          - name: Dump context
            env:
              gitub: ${{ toJson(github)}}
            run: echo "$github"
          - name: Dump job context
            env:
              job: ${{ toJson(job)}}
            run: echo "$job"
          - name: Dump steps context
            env:
              steps: ${{ toJson(steps)}}
            run: echo "$steps"
          - name: Dump runner context
            env:
              runner: ${{ toJson(runnner)}}
            run: echo "$runner"
          - name: Dump strategy context
            env:
              strategy: ${{ toJson(strategy)}}
            run: echo "$strategy"
          - name: Dump matrix context
            env:
              matrix: ${{ toJson(matrix)}}
            run: echo "$matrix"