name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Chectkout Repo
          uses: actions/checkout@v4

        - name: Welcome message
          run: |
            echo "Hello World! GitHub Aaction test"
            ls -ltrh
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, Im a DRAGON .... RAWS" > dragon.txt