name: Matrix

on:
  # Schedule a workflow to run every 2 minutes
  # schedule:
  #   - cron: '*/2 * * * *'
  worklow_dispatch:

jobs:
    deploy-on-ubuntu:
     strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
            os: [ubuntu-latest, ubuntu-20.04, windows-latest]
            images: [hello-world, haproxy]
            exclude:
                - images: alpine
                  os: windows-latest
            include:
                - images: [amd64/alpine]
                  os: ubuntu-20.04
     runs-on: ${{matrix.os}}
     steps:
        - name: Echo Docker Details
          run: docker info
        
        - name: Run Images on ${{matrix.images}} on machine ${{matrix.os}}
          run: docker run ${{matrix.images}}
          timeout-minutes: 1


        
